# Generated by Django 5.0.1 on 2024-01-25 17:25

from django.db import migrations


def populate_status(apps, schemaeditor):
    entries = {
        "to do": "An issue that has not yet been worked on",
        "in progress": "An issue actively being worked on",
        "done": "A completed issue"
    }
    Issues = apps.get_model("status", "Issues")
    for key, value in entries.items():
        issues_obj = Issues(name=key, description=value)
        issues_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
